### ISSUE TITLE
blank default argument for redis_url cause an exception

### ISSUE THREAD

**Issue by pprolancer** [gowhari/pyredisrpc#1]
when create a Server or Client object without specifying redis_url, I face witht this exception.

ValueError: Redis URL must specify one of the followingschemes (redis://, rediss://, unix://)

I think you need to set default redis_url to "redis://"

I have test that on python 3.6 and redis==3.2.0

**Comment by gowhari** [comment]
yes you are right, from redis==3.1.0 (Jan 29, 2019) it's mandatory.

**Comment by gowhari** [comment]
Fixed: 9784419

**Comment by pprolancer** [comment]
@gowhari 
Thanks for quick response!
we have this issue in both "Server" and "Client" class.
seems you have fixed that only in "Server" class. we have same issue in "Client" class as well.

**Comment by gowhari** [comment]
@pprolancer 
yes, now it's fixed.
